/* ============================================================================
   AI Marketing Creation Hub — content / data layer
   All copy lives here so sections stay presentational. Sets window.HUB.
   Agents reflect the real Creative Studio agent register.
   ============================================================================ */
(function () {
  // Resource resolver: in the standalone bundle, window.__resources[id] holds an
  // inlined blob URL; in the normal page it's undefined, so we fall back to the path.
  const R = (id, path) => (typeof window !== "undefined" && window.__resources && window.__resources[id]) || path;
  // Video resolver: in the standalone bundle videos are excluded for size —
  // if __resources exists but has no entry, return null so the play UI hides.
  const RV = (id, path) =>
    typeof window !== "undefined" && window.__resources
      ? window.__resources[id] || null
      : path;

  const CATEGORIES = [
    {
      id: "create",
      label: "Create",
      icon: "add-glyph",
      blurb: "Generate new assets, imagery, ads, landing pages, emails and social content.",
      tint: "var(--teal-200)",
    },
    {
      id: "adapt",
      label: "Adapt",
      icon: "list-view-compare",
      blurb: "Resize, convert and version approved assets across formats, channels and placements.",
      tint: "var(--brand-yellow)",
    },
    {
      id: "check",
      label: "Check",
      icon: "service-security-check",
      blurb: "Brand, quality and performance reviews that flag what needs a human eye.",
      tint: "var(--brand-orange)",
    },
    {
      id: "learn",
      label: "Learn",
      icon: "education",
      blurb: "Prompting help, brand answers and guidance that make AI outputs land on brand.",
      tint: "var(--brand-blue)",
    },
    {
      id: "govern",
      label: "Manage",
      icon: "data-security",
      blurb: "Asset libraries, design tokens, icon systems and project oversight.",
      tint: "var(--brand-purple)",
    },
  ];

  /* phases mirror the Creative Studio register:
     Idea 0–20 · Prototype 20–50 · Testing 50–80 · Live 80–100 */
  const STATUS = {
    idea: { label: "Idea", tone: "idea" },
    prototype: { label: "Prototype", tone: "prototype" },
    testing: { label: "Testing", tone: "testing" },
    live: { label: "Live", tone: "live" },
  };

  const AGENTS = [
    {
      id: "lp-builder",
      name: "LP Builder",
      icon: "document-empty",
      status: "live",
      progress: 100,
      categories: ["create"],
      featured: true,
      what: "Create campaign landing pages faster using approved templates and modules.",
      owner: "Dominik Böhme",
      target: ["HO", "B2B", "Seeker"],
      audience: ["Performance", "CRM", "Content"],
      tags: ["Landing Page", "Marketing"],
      link: "https://chatgpt.com/g/g-69839550ac988191bd3a3838d2b00d02-landing-page-builder",
    },
    {
      id: "email-builder",
      name: "Email Builder",
      icon: "message-email",
      status: "testing",
      progress: 70,
      categories: ["create"],
      featured: true,
      what: "Supports email creation based on reusable modules and templates.",
      owner: "Dominik Böhme",
      target: ["HO", "B2B", "Seeker", "Media", "Loft", "Content"],
      audience: ["Content", "Performance"],
      tags: ["Email", "Marketing"],
      link: null,
    },
    {
      id: "brand-channel",
      name: "Brand Assistant",
      icon: "chat",
      status: "live",
      progress: 90,
      categories: ["learn", "govern"],
      featured: true,
      what: "Get trusted brand answers, find approved assets and route new creative requests fast.",
      owner: "Peter Sijtsma",
      target: ["Creative Studio"],
      audience: ["All Marketing", "Content", "Social", "Events", "PR"],
      tags: ["Support"],
      link: "https://scout24.slack.com/archives/C026PM1HP2N",
    },
    {
      id: "is24-imagery",
      name: "Brand Imagery Builder",
      icon: "picture",
      status: "live",
      progress: 90,
      categories: ["create"],
      featured: true,
      what: "Create photorealistic, on-brand marketing imagery and variants from a rough brief.",
      owner: "Peter Sijtsma",
      target: ["HO", "B2B", "Seeker", "Content", "Social media", "Paid marketing"],
      audience: ["Brand", "Campaign", "Content", "Social"],
      tags: ["Image creation", "On brand"],
      link: "https://chatgpt.com/agents/a/agt_6a01c8992f848191b3f2957bc09bfaf3",
    },
    {
      id: "native-ad-imagery",
      name: "Native Ad Imagery Builder",
      icon: "immo-ad",
      status: "live",
      progress: 90,
      categories: ["create"],
      featured: true,
      what: "Create native-style ad imagery that feels at home in the placement while staying on brand.",
      owner: "Peter Sijtsma",
      target: ["Paid marketing", "Social media", "PPC"],
      audience: ["Performance", "Social", "Campaign"],
      tags: ["Ad creative", "Image creation"],
      link: "https://chatgpt.com/agents/a/agt_6a01c8992f848191b3f2957bc09bfaf3",
    },
    {
      id: "illustration-extender",
      name: "Illustration Assistant",
      icon: "edit",
      status: "live",
      progress: 90,
      categories: ["create"],
      featured: true,
      what: "Create on-brand illustrations from new briefs using our established visual style.",
      owner: "Peter Sijtsma",
      target: ["HO", "B2B", "Seeker", "Content", "Social media", "Paid marketing"],
      audience: ["Brand", "Content", "Campaign", "Design"],
      tags: ["Illustration"],
      link: "https://chatgpt.com/agents/a/agt_6a0d7bb452e081919258f38b342aa774",
    },
    {
      id: "governed-icons",
      name: "Governed Icon System",
      icon: "premium-2",
      status: "testing",
      progress: 60,
      categories: ["govern"],
      featured: true,
      what: "Keeps all our icons neat and the same, so they always look right everywhere we use them.",
      owner: "Peter Sijtsma",
      target: ["UX", "Engineering", "Product", "Marketing"],
      audience: ["Brand"],
      tags: ["Icons"],
      link: "https://claude.ai/design/p/d260a4c1-0159-4751-aee8-9ceb836c7593?file=Icon+System+Playbook.html&via=share",
    },
    {
      id: "loft-ad-designer",
      name: "LOFT Ad Designer",
      icon: "immo-ad",
      status: "testing",
      progress: 70,
      categories: ["create", "adapt"],
      featured: false,
      what: "A LOFT Facebook ad design agent that turns client assets into polished, on brand Meta ad variants and realistic Facebook style previews for fast review, reuse and sales.",
      owner: "Peter Sijtsma",
      target: ["Loft sales"],
      audience: ["Social", "Performance"],
      tags: ["Sales automation"],
      link: "https://www.figma.com/make/lT2AJ1LQJXw1ZOFLRJtL0v/ImmoScout24-Ad-Generator?t=zr1qdYdrzbS6zM2D-1",
    },
    {
      id: "ad-format-adapter",
      name: "Ad Format Adapter",
      icon: "list-view-compare",
      status: "prototype",
      progress: 25,
      categories: ["adapt"],
      featured: false,
      what: "Turns an existing ad into versions that fit different sizes and placements while keeping the main message, look and call to action clear.",
      owner: "Nadja De Col",
      target: ["PPC"],
      audience: ["Performance"],
      tags: ["PPC", "Paid ads", "SoMe assets"],
      link: "https://chatgpt.com/agents/a/agt_6a18363bc9248191a74e77441afed202",
    },
    {
      id: "gif-compression",
      name: "GIF Compression Agent",
      icon: "video",
      status: "testing",
      progress: 50,
      categories: ["adapt"],
      featured: false,
      what: "Turns short video clips into lightweight, polished GIFs while keeping them as close to the original as possible.",
      owner: "Nadja De Col",
      target: ["Email Marketing"],
      audience: ["Content"],
      tags: ["Email", "Marketing"],
      link: "https://chatgpt.com/agents/a/agt_6a16fdd863108191802a67e7cb7e4d83",
    },
    {
      id: "image-size-adapter",
      name: "Image Size Adapter",
      icon: "list-view-compare",
      status: "testing",
      progress: 60,
      categories: ["adapt"],
      featured: false,
      what: "Adapt source images into channel-ready formats — picking the right aspect ratios, protecting key content and recomposing layouts so outputs stay on brand.",
      owner: "Peter Sijtsma",
      target: ["Paid social", "Display", "PPC"],
      audience: ["Performance", "Social", "Content"],
      tags: ["Image adaptation", "Resizing"],
      link: "https://chatgpt.com/agents/a/agt_6a4114e819588191866e242691ee32da",
    },
    {
      id: "jpg-png-to-svg",
      name: "Convert JPG/PNG to SVG",
      icon: "picture",
      status: "testing",
      progress: 65,
      categories: ["adapt"],
      featured: false,
      what: "Convert an uploaded JPG or PNG illustration into a clean SVG — a faithful vector with a transparent background and no embedded raster image.",
      owner: "Peter Sijtsma",
      target: ["Creative team", "Content", "Marketing"],
      audience: ["Content", "Brand", "Design"],
      tags: ["Vector conversion", "Illustration"],
      link: "https://chatgpt.com/agents/a/agt_6a40f4cf557c8191a5d7066812008d24",
    },
    {
      id: "video-endcard-editor",
      name: "Video Endcard Editor",
      icon: "video",
      status: "testing",
      progress: 70,
      categories: ["adapt"],
      featured: false,
      what: "Add the correct brand endcard to any video without editing skills — just tell it the format and it does the rest.",
      owner: "Nadja De Col",
      target: ["B2B", "Content", "Social media"],
      audience: ["Content", "Social", "B2B"],
      tags: ["Video editing", "Endcards"],
      link: "https://chatgpt.com/agents/a/agt_6a3be82670e88191ad40f6ecdd1f7c42",
    },
    {
      id: "video-ad-prompter",
      name: "Video Ad Prompter",
      icon: "virtualtour",
      status: "idea",
      progress: 10,
      categories: ["create"],
      featured: false,
      what: "Turns a still ad or visual idea into clear video concepts, storyboards, scripts and prompts that a creator or video tool can use to make it move.",
      owner: "Nadja De Col",
      target: ["PPC"],
      audience: ["Performance", "Social"],
      tags: ["PPC", "Paid ads", "SoMe assets"],
      link: "https://chatgpt.com/agents/a/agt_6a1851f335908191b1c465f1a13a1a49",
    },
    {
      id: "ae-expression",
      name: "AE Expression Specialist",
      icon: "calculator",
      status: "prototype",
      progress: 35,
      categories: ["create"],
      featured: false,
      what: "Helps motion designers create, debug and refine After Effects expressions and rigs.",
      owner: "Henrik Östergaard",
      target: ["Video Experts"],
      audience: ["Content"],
      tags: ["Video production"],
      link: "https://chatgpt.com/agents/a/agt_6a183ef7e3a88191a23bf8a7664c5d74",
    },
    {
      id: "script-storyboard",
      name: "Script & Storyboard Agent",
      icon: "write-message",
      status: "testing",
      progress: 55,
      categories: ["create"],
      featured: false,
      what: "Turn a business message or product idea into a strong video concept, script and storyboard — tailored to the audience and goal.",
      owner: "Henrik Östergaard",
      target: ["Creative Studio", "Marketing", "Video"],
      audience: ["Content", "Brand", "Campaign"],
      tags: ["Video concept", "Scriptwriting"],
      link: "https://chatgpt.com/agents/a/agt_6a1da1d1ca988191a2d33f1b92f3d82a",
    },
    {
      id: "prompt-engineer",
      name: "Image & Video Prompt Engineer",
      icon: "bulls-eye",
      status: "prototype",
      progress: 35,
      categories: ["learn", "create"],
      featured: false,
      what: "Write better prompts for image and video models — tuned to each model's rules, strengths and limits, so you get accurate results faster.",
      owner: "Henrik Östergaard",
      target: ["Marketing", "Brand", "Creative Studio"],
      audience: ["All Marketing"],
      tags: ["Image Creation", "Video Creation"],
      link: "https://chatgpt.com/agents/a/agt_6a212cb79db081918a3f58739e0a12da",
    },
    {
      id: "design-direction",
      name: "Design Direction Partner",
      icon: "targeting",
      status: "prototype",
      progress: 40,
      categories: ["create", "learn"],
      featured: false,
      what: "A design direction partner that turns rough briefs, feedback and Figma context into clear visual direction and usable first pass design work quickly.",
      owner: "Peter Sijtsma",
      target: ["Creative Studio"],
      audience: ["Brand", "Content"],
      tags: ["Brainstorm", "Ideation"],
      link: "https://chatgpt.com/agents/a/agt_6a0475a7db288191bf1c3bba456c1d5b",
    },
    {
      id: "figma-token-architect",
      name: "Figma Token Architect",
      icon: "settings",
      status: "prototype",
      progress: 30,
      categories: ["govern"],
      featured: false,
      what: "A Design Token Architect that turns brand and subbrand inputs into clean, multi brand token systems with strict primitive, semantic and component layers ready for design and development.",
      owner: "Peter Sijtsma",
      target: ["B2B", "Subsidiaries", "Creative Studio"],
      audience: ["Brand"],
      tags: ["Scalable designs"],
      link: "https://chatgpt.com/agents/a/agt_6a10268bb3808191b1824a95f5bcf6c4",
    },
    {
      id: "figma-iab-html",
      name: "Figma to IAB HTML Ad Generator",
      icon: "link",
      status: "prototype",
      progress: 35,
      categories: ["adapt", "create"],
      featured: false,
      what: "An IAB HTML ad builder that turns Figma ad designs into production ready HTML5 display ads for IAB formats, with accessible markup, layout validation, export packaging and future animation presets.",
      owner: "Marcus Dillgen",
      target: ["Marketing Designers", "PPC / Ad Operations", "Campaign Managers", "Frontend Developers"],
      audience: ["Performance"],
      tags: ["IAB", "HTML5 Ads", "Figma to Code", "Display Advertising", "Static Ads", "Responsive Ads", "Animated Ads", "QA Automation"],
      link: null,
    },
    {
      id: "icon-designer",
      name: "Icon Designer",
      icon: "offer",
      status: "idea",
      progress: 5,
      categories: ["create", "govern"],
      featured: false,
      what: "Reviews Creative Studio icon tickets, interprets IS24 iconography guidance and prepares clear, on brand icon proposals for review.",
      owner: "Peter Sijtsma",
      target: ["UX", "HO", "B2B", "Seeker", "Content", "Social media", "Paid marketing"],
      audience: ["Brand"],
      tags: ["Icon library"],
      link: "https://chatgpt.com/agents/a/agt_6a0192990a988191a6dc47ce51db8c4e",
    },
    {
      id: "brand-worldbuilding",
      name: "IS24 Brand Worldbuilding Agent",
      icon: "camera",
      status: "idea",
      progress: 20,
      categories: ["create"],
      featured: false,
      what: "An IS24 Visual Brand Agent that generates target group specific, brand consistent imagery for Seeker, Homeowner and Professionals by translating empirically researched visual constraints into structured prompts, so every asset feels like one coherent IS24 world.",
      owner: "Mono Jacobi",
      target: ["HO", "Seeker", "B2B", "Content", "Paid marketing"],
      audience: ["Brand", "Content"],
      tags: ["Image creation"],
      link: null,
    },
    {
      id: "brand-design-check",
      name: "Brand Design Check",
      icon: "eye-check",
      status: "idea",
      progress: 10,
      categories: ["check"],
      featured: false,
      what: "Reviews designs against brand guidelines and identifies inconsistencies in visual identity and messaging.",
      owner: "Alexander Penkin",
      target: ["Brand", "Marketing", "Design Teams"],
      audience: ["Brand"],
      tags: ["Brand", "Design"],
      link: null,
    },
    {
      id: "marketing-performance",
      name: "Marketing Design Performance",
      icon: "statistic-with-arrow-up",
      status: "idea",
      progress: 0,
      categories: ["check"],
      featured: false,
      what: "Analyzes asset and marketing performance using KPIs, reach, CTR, conversion data and cost efficiency, compares results against targets or benchmarks, and recommends specific actions without inventing data or causation.",
      owner: "Peter Sijtsma",
      target: ["Creative Studio", "Performance"],
      audience: ["Performance"],
      tags: ["Performance marketing"],
      link: null,
    },
    {
      id: "asset-library",
      name: "Asset Library Agent",
      icon: "search",
      status: "idea",
      progress: 0,
      categories: ["learn", "govern"],
      featured: false,
      what: "Helps users find, trust, archive and safely reuse assets across SharePoint, Frontify and Figma by normalizing metadata, identifying approved versions, surfacing the best source of truth result and flagging archive candidates.",
      owner: "Peter Sijtsma",
      target: ["UX", "HO", "B2B", "Seeker", "Content", "Social media", "Paid marketing"],
      audience: ["All Marketing"],
      tags: ["Asset library"],
      link: null,
    },
    {
      id: "design-pm",
      name: "Design Project Management",
      icon: "calendar-check",
      status: "idea",
      progress: 5,
      categories: ["govern"],
      featured: false,
      what: "Helps the design team manage current projects by using past project context to find precedent, summarize status, identify blockers and missing decisions, and turn notes or Slack threads into clear next actions.",
      owner: "Peter Sijtsma",
      target: ["B2B", "Event", "Brand"],
      audience: ["Events", "All Marketing"],
      tags: ["Project management"],
      link: null,
    },
    {
      id: "ppt-creator",
      name: "PPT Creator",
      icon: "dashboard",
      status: "idea",
      progress: 10,
      categories: ["create"],
      featured: false,
      what: "Supports the creation of presentations about AI agents, including structure, content generation and storytelling.",
      owner: "Alexander Penkin",
      target: ["Product", "Marketing", "Org"],
      audience: ["All Marketing"],
      tags: ["Presentation", "Enablement", "Org"],
      link: null,
    },
    {
      id: "canva-agent",
      name: "Canva Agent",
      icon: "share",
      status: "idea",
      progress: 10,
      categories: ["create"],
      featured: false,
      what: "Integrates ChatGPT with Canva to automate content creation, design generation and marketing asset production.",
      owner: "Alexander Penkin",
      target: ["Marketing", "Brand", "Content Teams"],
      audience: ["Content", "Social"],
      tags: ["PPC", "Marketing"],
      link: null,
    },
    {
      id: "figma-ads-creator",
      name: "Figma Ads Creator",
      icon: "immo-ad",
      status: "idea",
      progress: 10,
      categories: ["create", "adapt"],
      featured: false,
      what: "Automates the creation, adaptation and optimization of advertising creatives and campaign assets in Figma.",
      owner: "Alexander Penkin",
      target: ["Marketing", "Brand", "PPC"],
      audience: ["Performance", "Social"],
      tags: ["PPC", "Marketing", "Figma"],
      link: null,
    },
  ];

  const RECOMMENDED = ["lp-builder", "is24-imagery", "brand-channel"];

  const START_STEPS = [
    {
      icon: "video",
      title: "Watch the 3 minute intro",
      body: "What the hub is, what Creative Studio owns, and how to get value in week one.",
      cta: "Watch intro",
    },
    {
      icon: "chat",
      title: "Learn basic prompting",
      body: "Five principles that make AI outputs land closer to on brand on the first try.",
      cta: "Open guide",
    },
    {
      icon: "service-security-check",
      title: "Know what needs review",
      body: "A short, honest list of where AI is a great first draft, and where it is not.",
      cta: "See guardrails",
    },
    {
      icon: "calendar-check",
      title: "Book a sparring session",
      body: "Bring a real use case. Creative Studio helps you set it up properly in 30 minutes.",
      cta: "Request sparring",
    },
  ];

  const TUTORIALS = [
    {
      id: "t1",
      agent: "LP Builder",
      title: "Build a landing page from modules",
      duration: "3 min",
      level: "Beginner",
      photo: R("photoCoupleTablet", "assets/photos/couple-tablet.jpg"),
    },
    {
      id: "t2",
      agent: "Brand Imagery Builder",
      title: "Photorealistic imagery from a rough brief",
      duration: "5 min",
      level: "Beginner",
      photo: R("photoTutorialImageBuilderPoster", "assets/photos/tutorial-image-builder-poster.jpg"),
      videoUrl: RV("videoTutorialImageBuilder", "assets/tutorial-image-builder.mp4"),
    },
    {
      id: "t2b",
      agent: "Script & Storyboard Agent",
      title: "From idea to script and storyboard",
      duration: "1 min",
      level: "Beginner",
      photo: R("photoTutorialScriptStoryboardPoster", "assets/photos/tutorial-script-storyboard-poster.jpg"),
      videoUrl: RV("videoTutorialScriptStoryboard", "assets/tutorial-script-storyboard.mp4"),
    },
    {
      id: "t-endcard",
      agent: "Video Endcard Editor",
      title: "Add a brand endcard to your video",
      duration: "2 min",
      level: "Beginner",
      photo: R("photoTutorialVideoEndcardEditorPoster", "assets/photos/tutorial-video-endcard-editor-poster.jpg"),
      videoUrl: RV("videoTutorialVideoEndcardEditor", "assets/tutorial-video-endcard-editor.mp4"),
    },
    {
      id: "t3",
      agent: "Brand Assistant",
      title: "Learn Brand Assistant in 3 Minutes",
      duration: "3 min",
      level: "Beginner",
      photo: R("photoP114", "assets/photos/p-114.jpg"),
    },
    {
      id: "t4",
      agent: "Email Builder",
      title: "Assemble an email from reusable modules",
      duration: "4 min",
      level: "Intermediate",
      photo: R("photoP049", "assets/photos/p-049.jpg"),
    },
    {
      id: "t5",
      agent: "Illustration Assistant",
      title: "Learn Illustration Assistant in 3 Minutes",
      duration: "3 min",
      level: "Beginner",
      photo: R("photoP121", "assets/photos/p-121.jpg"),
    },
  ];

  const TUTORIAL_FORMAT = [
    "What the agent is for",
    "How to start",
    "Example input",
    "Example output",
    "How to improve the result",
    "What to check before using",
    "When to contact Creative Studio",
  ];

  const GUARDRAILS = [
    {
      id: "always",
      tone: "ok",
      icon: "accept-glyph",
      title: "Good to go",
      sub: "Fine as a first draft, with a quick human read.",
      items: [
        "Early visual exploration and mood finding",
        "Internal concepts and stakeholder alignment",
        "Recurring mailing & CRM imagery drafts",
        "Caption and tone variations to react to",
        "Resizing approved masters to channel formats",
      ],
    },
    {
      id: "careful",
      tone: "warn",
      icon: "caution-glyph",
      title: "Be careful",
      sub: "Usable, but check these before anything ships.",
      items: [
        "Contrast & accessibility on text over image",
        "Logo clear space and minimum sizes",
        "Faces, hands and fine product detail",
        "Tone on sensitive or emotional topics",
        "Consistency across a multi asset set",
      ],
    },
    {
      id: "ask",
      tone: "ask",
      icon: "question-mark-glyph",
      title: "Ask Creative Studio",
      sub: "Bring us in before you use it.",
      items: [
        "Hero & high impact brand campaign assets",
        "Legal, rights sensitive or regulated content",
        "Anything claiming facts, pricing or results",
        "New brand expressions or visual language",
        "Anything going out at large media spend",
      ],
    },
  ];

  const METRICS = [
    { value: "1,240", label: "Agent visits", hint: "last 30 days", icon: "statistics", trend: "+18%" },
    { value: "380", label: "Agent uses", hint: "drafts generated", icon: "add-glyph", trend: "+24%" },
    { value: "7", label: "Agent owners", hint: "across marketing", icon: "persons", trend: "+2" },
    { value: "~120h", label: "Time saved", hint: "estimated, monthly", icon: "stopwatch", trend: "new" },
    { value: "640", label: "Assets created", hint: "first drafts", icon: "picture", trend: "+31%" },
    { value: "4.4/5", label: "Feedback score", hint: "agent usefulness", icon: "rating-star-full", trend: "+0.3" },
  ];

  const SHOWCASES = [
    {
      id: "s1",
      photo: R("photoStroller", "assets/photos/stroller.jpg"),
      useCase: "Seasonal CRM mailing series",
      team: "CRM Team",
      agent: "Brand Imagery Builder",
      owner: "Peter Sijtsma",
      impact: "12 mailing variants drafted in an afternoon, one review cycle.",
      learning: "Tight, brand aligned prompts removed two rounds of back and forth.",
    },
    {
      id: "s2",
      photo: R("photoP121", "assets/photos/p-121.jpg"),
      useCase: "Performance display, 8 formats",
      team: "Performance Marketing",
      agent: "Ad Format Adapter",
      owner: "Nadja De Col",
      impact: "One approved master adapted to 8 placements, fully on grid.",
      learning: "Safe area rules in the agent kept logos and CTAs intact.",
    },
    {
      id: "s3",
      photo: R("photoFamilyCouch", "assets/photos/family-couch.jpg"),
      useCase: "Campaign brand alignment",
      team: "Content Team",
      agent: "Brand Assistant",
      owner: "Peter Sijtsma",
      impact: "One source of truth for brand answers across the whole campaign.",
      learning: "Approved assets surfaced instantly, with no guesswork.",
    },
  ];

  window.HUB = {
    CATEGORIES,
    STATUS,
    AGENTS,
    RECOMMENDED,
    START_STEPS,
    TUTORIALS,
    TUTORIAL_FORMAT,
    GUARDRAILS,
    METRICS,
    SHOWCASES,
  };
})();
